- name: Install ChromeDriver
  run: |
    CHROMEDRIVER_VERSION="114.0.5735.90"  # Specify a known working version
    echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
    
    CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"
    
    wget -q -O /tmp/chromedriver.zip "$CHROMEDRIVER_URL" || { echo "Failed to download ChromeDriver"; exit 1; }
    
    echo "Unzipping ChromeDriver"
    sudo unzip -o /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ || { echo "Failed to unzip ChromeDriver"; exit 1; }
    
    echo "Setting permissions for ChromeDriver"
    sudo chmod +x /usr/local/bin/chromedriver
    
    echo "ChromeDriver installation complete"
    chromedriver --version
  shell: /usr/bin/bash -e {0}
